<?php

namespace Database\Seeders;

use App\Models\AccountCompany;
use Illuminate\Database\Seeder;

class AccountCompanySeeder extends Seeder
{
    public function run(): void
    {
        $accounts = [
            [
                'account_name' => 'PT Maju Bersama',
                'sources_id' => 4,
                'types_accounts_companies_id' => 1,
                'website' => 'https://majubersama.com',
                'description' => 'Perusahaan teknologi solusi enterprise',
                'segmentation_id' => 1,
                'business_entities_id' => 7,
                'business_values_id' => 1,
                'interaction_levels_id' => 1,
                'phone' => '021-5551234',
                'account_owner_id' => 1,
                'address_billing_street' => 'Jl. Sudirman No. 123',
                'address_billing_city' => 'Jakarta Selatan',
                'address_billing_province' => 'DKI Jakarta',
                'address_billing_postal_code' => '12950',
                'address_billing_country' => 'Indonesia',
                'address_shipping_street' => 'Jl. Sudirman No. 123',
                'address_shipping_city' => 'Jakarta Selatan',
                'address_shipping_province' => 'DKI Jakarta',
                'address_shipping_postal_code' => '12950',
                'address_shipping_country' => 'Indonesia',
                'status' => 'Active',
            ],
            [
                'account_name' => 'CV Jaya Abadi',
                'sources_id' => 5,
                'types_accounts_companies_id' => 2,
                'website' => 'https://jayaabadi.co.id',
                'description' => 'Distributor alat kesehatan',
                'segmentation_id' => 2,
                'business_entities_id' => 7,
                'business_values_id' => 2,
                'interaction_levels_id' => 2,
                'phone' => '031-8884567',
                'account_owner_id' => 1,
                'address_billing_street' => 'Jl. Raya Darmo No. 45',
                'address_billing_city' => 'Surabaya',
                'address_billing_province' => 'Jawa Timur',
                'address_billing_postal_code' => '60265',
                'address_billing_country' => 'Indonesia',
                'address_shipping_street' => 'Jl. Raya Darmo No. 45',
                'address_shipping_city' => 'Surabaya',
                'address_shipping_province' => 'Jawa Timur',
                'address_shipping_postal_code' => '60265',
                'address_shipping_country' => 'Indonesia',
                'status' => 'Active',
            ],
            [
                'account_name' => 'PT Nusantara Digital',
                'sources_id' => 4,
                'types_accounts_companies_id' => 1,
                'website' => 'https://nusadigital.id',
                'description' => 'Startup fintech pembayaran digital',
                'segmentation_id' => 3,
                'business_entities_id' => 8,
                'business_values_id' => 4,
                'interaction_levels_id' => 2,
                'phone' => '022-7778901',
                'account_owner_id' => 1,
                'address_billing_street' => 'Jl. Asia Afrika No. 88',
                'address_billing_city' => 'Bandung',
                'address_billing_province' => 'Jawa Barat',
                'address_billing_postal_code' => '40112',
                'address_billing_country' => 'Indonesia',
                'address_shipping_street' => 'Jl. Asia Afrika No. 88',
                'address_shipping_city' => 'Bandung',
                'address_shipping_province' => 'Jawa Barat',
                'address_shipping_postal_code' => '40112',
                'address_shipping_country' => 'Indonesia',
                'status' => 'Active',
            ],
            [
                'account_name' => 'UD Sumber Makmur',
                'sources_id' => 5,
                'types_accounts_companies_id' => 2,
                'website' => null,
                'description' => 'Supplier bahan baku makanan',
                'segmentation_id' => 2,
                'business_entities_id' => 7,
                'business_values_id' => 2,
                'interaction_levels_id' => 3,
                'phone' => '0274-3339876',
                'account_owner_id' => 1,
                'address_billing_street' => 'Jl. Malioboro No. 15',
                'address_billing_city' => 'Yogyakarta',
                'address_billing_province' => 'DIY Yogyakarta',
                'address_billing_postal_code' => '55121',
                'address_billing_country' => 'Indonesia',
                'address_shipping_street' => 'Jl. Malioboro No. 15',
                'address_shipping_city' => 'Yogyakarta',
                'address_shipping_province' => 'DIY Yogyakarta',
                'address_shipping_postal_code' => '55121',
                'address_shipping_country' => 'Indonesia',
                'status' => 'Active',
            ],
            [
                'account_name' => 'PT Global Investama',
                'sources_id' => 4,
                'types_accounts_companies_id' => 1,
                'website' => 'https://globalinvestama.com',
                'description' => 'Perusahaan investasi dan manajemen aset',
                'segmentation_id' => 1,
                'business_entities_id' => 8,
                'business_values_id' => 1,
                'interaction_levels_id' => 1,
                'phone' => '021-6665432',
                'account_owner_id' => 1,
                'address_billing_street' => 'Jl. MH Thamrin No. 10',
                'address_billing_city' => 'Jakarta Pusat',
                'address_billing_province' => 'DKI Jakarta',
                'address_billing_postal_code' => '10340',
                'address_billing_country' => 'Indonesia',
                'address_shipping_street' => 'Jl. MH Thamrin No. 10',
                'address_shipping_city' => 'Jakarta Pusat',
                'address_shipping_province' => 'DKI Jakarta',
                'address_shipping_postal_code' => '10340',
                'address_shipping_country' => 'Indonesia',
                'status' => 'Active',
            ],
        ];

        foreach ($accounts as $account) {
            AccountCompany::firstOrCreate(
                ['account_name' => $account['account_name']],
                $account
            );
        }
    }
}
