<?php

namespace Database\Seeders;

use App\Models\AccountContact;
use Illuminate\Database\Seeder;

class AccountContactSeeder extends Seeder
{
    public function run(): void
    {
        $contacts = [
            [
                'account_companies_id' => 1,
                'full_name' => 'Budi Santoso',
                'salutation' => 'Bapak',
                'email' => 'budi@majubersama.com',
                'phone' => '021-5551234',
                'mobile' => '08123456789',
                'job_titles_id' => 1,
                'sources_id' => 4,
                'role_in_projects_id' => 1,
                'contact_methods_id' => 1,
                'divisions_id' => 1,
                'contact_owner_id' => 1,
                'address_street' => 'Jl. Sudirman No. 123',
                'address_city' => 'Jakarta Selatan',
                'address_province' => 'DKI Jakarta',
                'address_postal_code' => '12950',
                'address_country' => 'Indonesia',
                'lead_status' => 'Qualified',
                'status' => 'Active',
            ],
            [
                'account_companies_id' => 1,
                'full_name' => 'Siti Rahayu',
                'salutation' => 'Ibu',
                'email' => 'siti@majubersama.com',
                'phone' => '021-5551235',
                'mobile' => '08234567890',
                'job_titles_id' => 2,
                'sources_id' => 5,
                'role_in_projects_id' => 2,
                'contact_methods_id' => 2,
                'divisions_id' => 3,
                'contact_owner_id' => 1,
                'address_street' => 'Jl. Sudirman No. 123',
                'address_city' => 'Jakarta Selatan',
                'address_province' => 'DKI Jakarta',
                'address_postal_code' => '12950',
                'address_country' => 'Indonesia',
                'lead_status' => 'New',
                'status' => 'Active',
            ],
            [
                'account_companies_id' => 2,
                'full_name' => 'Ahmad Hidayat',
                'salutation' => 'Bapak',
                'email' => 'ahmad@jayaabadi.co.id',
                'phone' => '031-8884567',
                'mobile' => '08345678901',
                'job_titles_id' => 3,
                'sources_id' => 5,
                'role_in_projects_id' => 3,
                'contact_methods_id' => 3,
                'divisions_id' => 2,
                'contact_owner_id' => 1,
                'address_street' => 'Jl. Raya Darmo No. 45',
                'address_city' => 'Surabaya',
                'address_province' => 'Jawa Timur',
                'address_postal_code' => '60265',
                'address_country' => 'Indonesia',
                'lead_status' => 'Contacted',
                'status' => 'Active',
            ],
            [
                'account_companies_id' => 2,
                'full_name' => 'Dewi Lestari',
                'salutation' => 'Ibu',
                'email' => 'dewi@jayaabadi.co.id',
                'phone' => '031-8884568',
                'mobile' => '08456789012',
                'job_titles_id' => 4,
                'sources_id' => 7,
                'role_in_projects_id' => 4,
                'contact_methods_id' => 2,
                'divisions_id' => 4,
                'contact_owner_id' => 1,
                'address_street' => 'Jl. Raya Darmo No. 45',
                'address_city' => 'Surabaya',
                'address_province' => 'Jawa Timur',
                'address_postal_code' => '60265',
                'address_country' => 'Indonesia',
                'lead_status' => 'New',
                'status' => 'Active',
            ],
            [
                'account_companies_id' => 3,
                'full_name' => 'Rudi Hartono',
                'salutation' => 'Bapak',
                'email' => 'rudi@nusadigital.id',
                'phone' => '022-7778901',
                'mobile' => '08567890123',
                'job_titles_id' => 2,
                'sources_id' => 4,
                'role_in_projects_id' => 1,
                'contact_methods_id' => 1,
                'divisions_id' => 1,
                'contact_owner_id' => 1,
                'address_street' => 'Jl. Asia Afrika No. 88',
                'address_city' => 'Bandung',
                'address_province' => 'Jawa Barat',
                'address_postal_code' => '40112',
                'address_country' => 'Indonesia',
                'lead_status' => 'Qualified',
                'status' => 'Active',
            ],
            [
                'account_companies_id' => 3,
                'full_name' => 'Maria Clara',
                'salutation' => 'Ibu',
                'email' => 'maria@nusadigital.id',
                'phone' => '022-7778902',
                'mobile' => '08678901234',
                'job_titles_id' => 1,
                'sources_id' => 8,
                'role_in_projects_id' => 2,
                'contact_methods_id' => 5,
                'divisions_id' => 5,
                'contact_owner_id' => 1,
                'address_street' => 'Jl. Asia Afrika No. 88',
                'address_city' => 'Bandung',
                'address_province' => 'Jawa Barat',
                'address_postal_code' => '40112',
                'address_country' => 'Indonesia',
                'lead_status' => 'Contacted',
                'status' => 'Active',
            ],
            [
                'account_companies_id' => 4,
                'full_name' => 'Dian Permata',
                'salutation' => 'Ibu',
                'email' => 'dian@sumbermakmur.id',
                'phone' => '0274-3339876',
                'mobile' => '08789012345',
                'job_titles_id' => 4,
                'sources_id' => 5,
                'role_in_projects_id' => 5,
                'contact_methods_id' => 3,
                'divisions_id' => 5,
                'contact_owner_id' => 1,
                'address_street' => 'Jl. Malioboro No. 15',
                'address_city' => 'Yogyakarta',
                'address_province' => 'DIY Yogyakarta',
                'address_postal_code' => '55121',
                'address_country' => 'Indonesia',
                'lead_status' => 'New',
                'status' => 'Active',
            ],
            [
                'account_companies_id' => 5,
                'full_name' => 'Anton Wijaya',
                'salutation' => 'Bapak',
                'email' => 'anton@globalinvestama.com',
                'phone' => '021-6665432',
                'mobile' => '08890123456',
                'job_titles_id' => 3,
                'sources_id' => 6,
                'role_in_projects_id' => 3,
                'contact_methods_id' => 4,
                'divisions_id' => 3,
                'contact_owner_id' => 1,
                'address_street' => 'Jl. MH Thamrin No. 10',
                'address_city' => 'Jakarta Pusat',
                'address_province' => 'DKI Jakarta',
                'address_postal_code' => '10340',
                'address_country' => 'Indonesia',
                'lead_status' => 'Unqualified',
                'status' => 'Active',
            ],
        ];

        foreach ($contacts as $contact) {
            AccountContact::firstOrCreate(
                ['email' => $contact['email']],
                $contact
            );
        }
    }
}
